In [2]:
import pandas as pd

In [3]:
citibike202101 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202101-citibike-tripdata.csv")
citibike202101.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2513,2021-01-01 00:00:11.9020,2021-01-01 00:42:05.2260,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47812,Customer,1969,0
1,2519,2021-01-01 00:00:15.0960,2021-01-01 00:42:14.9780,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47571,Customer,1969,0
2,1207,2021-01-01 00:00:28.9300,2021-01-01 00:20:36.6510,3144,E 81 St & Park Ave,40.776777,-73.959010,3724,7 Ave & Central Park South,40.766741,-73.979069,37451,Subscriber,2002,1
3,2506,2021-01-01 00:00:32.7130,2021-01-01 00:42:19.3980,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,48884,Customer,2002,1
4,959,2021-01-01 00:00:35.3650,2021-01-01 00:16:34.6010,534,Water - Whitehall Plaza,40.702551,-74.012723,332,Cherry St,40.712199,-73.979481,26837,Customer,2002,1

In [4]:
citibike202012 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202012-citibike-tripdata.csv")
citibike202011 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202011-citibike-tripdata.csv")
citibike202010 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202010-citibike-tripdata.csv")
citibike202009 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202009-citibike-tripdata.csv")
citibike202008 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202008-citibike-tripdata.csv")
citibike202007 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202007-citibike-tripdata.csv")
citibike202006 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202006-citibike-tripdata.csv")
citibike202005 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202005-citibike-tripdata.csv")
citibike202004 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202004-citibike-tripdata.csv")
citibike202003 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202003-citibike-tripdata.csv")
citibike202002 = pd.read_csv("/Users/marinaduarte/Documents/Tableu HW/202002-citibike-tripdata.csv")

In [9]:
frames = [citibike202010, citibike202009, citibike202008, citibike202007, citibike202006, citibike202005, citibike202004, citibike202003]

In [10]:
final = pd.concat(frames)
final

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1403,2020-10-01 00:00:10.7870,2020-10-01 00:23:34.5400,224,Spruce St & Nassau St,40.711464,-74.005524,3347,Van Brunt St & Wolcott St,40.677343,-74.012751,39079,Subscriber,1995,1
1,462,2020-10-01 00:00:18.2390,2020-10-01 00:08:00.5710,3161,W 76 St & Columbus Ave,40.780184,-73.977285,3158,W 63 St & Broadway,40.771639,-73.982614,41267,Subscriber,1998,2
2,770,2020-10-01 00:00:21.3070,2020-10-01 00:13:12.0840,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,3761,Cedar St & Myrtle Ave,40.697842,-73.926241,47398,Customer,1996,1
3,233,2020-10-01 00:00:25.0080,2020-10-01 00:04:18.6410,3141,1 Ave & E 68 St,40.765005,-73.958185,464,E 56 St & 3 Ave,40.759345,-73.967597,36482,Subscriber,1993,1
4,126,2020-10-01 00:00:25.3100,2020-10-01 00:02:32.1330,335,Washington Pl & Broadway,40.729039,-73.994046,229,Great Jones St,40.727434,-73.993790,45319,Subscriber,1989,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068452,137,2020-03-31 23:56:06.0490,2020-03-31 23:58:23.3880,422,W 59 St & 10 Ave,40.770513,-73.988038,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,18851,Subscriber,1989,2
1068453,1548,2020-03-31 23:57:27.6850,2020-04-01 00:23:16.4110,523,W 38 St & 8 Ave,40.754666,-73.991382,442,W 27 St & 7 Ave,40.746647,-73.993915,36539,Subscriber,1993,1
1068454,308,2020-03-31 23:58:00.2690,2020-04-01 00:03:08.9500,528,2 Ave & E 31 St,40.742909,-73.977061,487,E 20 St & FDR Drive,40.733143,-73.975739,43023,Subscriber,1982,1
1068455,872,2020-03-31 23:58:42.9010,2020-04-01 00:13:15.5860,3043,Lewis Ave & Decatur St,40.681460,-73.934903,3755,DeKalb Ave & Franklin Ave,40.690648,-73.957462,43073,Customer,1990,1
1068456,306,2020-03-31 23:59:17.2580,2020-04-01 00:04:23.8880,3721,31 St & Newtown Ave,40.767549,-73.920933,3592,Crescent St & Broadway,40.763359,-73.928647,39373,Subscriber,1974,1

In [11]:
final.loc[final['gender'] == 0,'gender'] = 'unknown'
final.loc[final['gender'] == 1,'gender'] = 'male'
final.loc[final['gender'] == 2,'gender'] = 'female'
final.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1403,2020-10-01 00:00:10.7870,2020-10-01 00:23:34.5400,224,Spruce St & Nassau St,40.711464,-74.005524,3347,Van Brunt St & Wolcott St,40.677343,-74.012751,39079,Subscriber,1995,male
1,462,2020-10-01 00:00:18.2390,2020-10-01 00:08:00.5710,3161,W 76 St & Columbus Ave,40.780184,-73.977285,3158,W 63 St & Broadway,40.771639,-73.982614,41267,Subscriber,1998,female
2,770,2020-10-01 00:00:21.3070,2020-10-01 00:13:12.0840,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,3761,Cedar St & Myrtle Ave,40.697842,-73.926241,47398,Customer,1996,male
3,233,2020-10-01 00:00:25.0080,2020-10-01 00:04:18.6410,3141,1 Ave & E 68 St,40.765005,-73.958185,464,E 56 St & 3 Ave,40.759345,-73.967597,36482,Subscriber,1993,male
4,126,2020-10-01 00:00:25.3100,2020-10-01 00:02:32.1330,335,Washington Pl & Broadway,40.729039,-73.994046,229,Great Jones St,40.727434,-73.993790,45319,Subscriber,1989,male

In [12]:
final.to_csv("/Users/marinaduarte/Documents/Tableu HW/final.csv")